
const LS_DOCS='ct_docs_v2';
const $=s=>document.querySelector(s);
const read=(k,f)=>{ try{const v=localStorage.getItem(k); return v?JSON.parse(v):f }catch(e){ return f } };
const write=(k,v)=>{ try{localStorage.setItem(k,JSON.stringify(v))}catch(e){} };
const uid=()=>Math.random().toString(36).slice(2,9);
const toast=t=>{ let el=document.getElementById('toast'); if(!el){ el=document.createElement('div'); el.id='toast'; el.className='toast'; document.body.appendChild(el);} el.textContent=t; el.setAttribute('show',''); setTimeout(()=>el.removeAttribute('show'),1200);};
function md(text){ return (text||'').replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\*(.*?)\*/g,'<i>$1</i>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>'); }
function line(p){ return `<div class='item'><div class='item-head'><div style='min-width:0'><div class='item-line'>${p.title||'—'}</div><div class='item-sub'>${(p.tags||[]).join(', ')}</div></div><div class='row'><button class='btn sm' data-open='${p.id}'>Öffnen</button><button class='btn sm' data-fav='${p.id}'>${p.fav?'★':'☆'}</button></div></div></div>`; }
function redraw(){ const q=$('#q').value.toLowerCase(); const favOnly=$('#favOnly').dataset.on==='1'; const arr=read(LS_DOCS,[]).filter(x=> (favOnly?x.fav:true) && (q? (x.title||'').toLowerCase().includes(q) || (x.body||'').toLowerCase().includes(q):true)); $('#list').innerHTML=arr.length? arr.map(line).join('') : '<div class="small">Keine Seiten</div>'; $('#list').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEd(b.dataset.open)); $('#list').querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{ const id=b.dataset.fav; const a=read(LS_DOCS,[]); const p=a.find(x=>x.id===id); p.fav=!p.fav; write(LS_DOCS,a); redraw(); }); }
let CUR=null;
function openEd(id){ const a=read(LS_DOCS,[]); let p=a.find(x=>x.id===id); if(!p){ p={id:uid(), title:'', tags:[], body:'', fav:false}; a.push(p); write(LS_DOCS,a); } CUR=p; $('#dTitle').value=p.title||''; $('#dTags').value=(p.tags||[]).join(', '); $('#dBody').value=p.body||''; $('#preview').style.display='none'; $('#ed').setAttribute('open',''); }
function saveEd(){ const a=read(LS_DOCS,[]); const p=a.find(x=>x.id===CUR.id); p.title=$('#dTitle').value.trim(); p.tags=($('#dTags').value||'').split(',').map(s=>s.trim()).filter(Boolean); p.body=$('#dBody').value; write(LS_DOCS,a); $('#ed').removeAttribute('open'); redraw(); toast('Gespeichert'); }
function delEd(){ if(!CUR) return; if(confirm('Seite löschen?')){ const n=read(LS_DOCS,[]).filter(x=>x.id!==CUR.id); write(LS_DOCS,n); $('#ed').removeAttribute('open'); redraw(); toast('Gelöscht'); } }
function exportJson(){ const data=JSON.stringify(read(LS_DOCS,[])); const blob=new Blob([data],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='cititool_docs.json'; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(url); a.remove();},400); }
function importJson(){ const f=$('#impFile'); f.value=''; f.click(); f.onchange=()=>{ const file=f.files[0]; if(!file) return; const r=new FileReader(); r.onload=()=>{ try{ const arr=JSON.parse(r.result); write(LS_DOCS,arr); redraw(); toast('Importiert'); }catch(e){ alert('Falsches JSON'); } }; r.readAsText(file); }; }
document.addEventListener('DOMContentLoaded',()=>{ if(!read(LS_DOCS,[]).length){ write(LS_DOCS,[ {id:uid(), title:'Nullpunkt-Check', tags:['Setup','Prüfen'], body:'**G54** prüfen, *Taster* kalibrieren.', fav:true}, {id:uid(), title:'VDI30 Halter', tags:['Werkzeug'], body:'Anzugsmoment: `35 Nm`.', fav:false} ]); } redraw(); $('#btnNew').onclick=()=>openEd(null); $('#edClose').onclick=()=>$('#ed').removeAttribute('open'); $('#dSave').onclick=saveEd; $('#dDelete').onclick=delEd; $('#q').oninput=redraw; $('#btnPreview').onclick=()=>{ const html=md($('#dBody').value); const pv=$('#preview'); pv.innerHTML=html; pv.style.display='block'; }; $('#btnExport').onclick=exportJson; '#btnImport' in window && document.getElementById('btnImport').addEventListener('click', importJson); $('#favOnly').onclick=()=>{ const b=$('#favOnly'); b.dataset.on=b.dataset.on==='1'?'0':'1'; b.textContent=b.dataset.on==='1'?'Nur Favoriten (an)':'Nur Favoriten'; redraw(); }; });
